# Generated by Django 5.1.7 on 2025-03-29 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesajınız')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesajınız')),
                ('datetime', models.DateTimeField()),
                ('how_many_guests', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('opening_time', models.CharField(max_length=50, verbose_name='Çalışma saatleri')),
                ('welcome_message', models.CharField(max_length=75, verbose_name='Hoşgeldiniz mesajı')),
                ('home_header_text', models.TextField(verbose_name='Ana sayfa header yazı')),
                ('home_header_big_text_1', models.CharField(max_length=50, verbose_name='Ana sayfa header büyük yazı sol')),
                ('home_header_big_text', models.TextField(verbose_name='Ana sayfa header büyük yazı sağ')),
                ('home_header_button', models.CharField(max_length=50, verbose_name='Ana sayfa Header button')),
                ('home_header_button_link', models.URLField(verbose_name='Ana sayfa Header button URL')),
                ('footer_text', models.CharField(max_length=150, verbose_name='Footer yazı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('button_title', models.CharField(max_length=30)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('m_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Orta Boy')),
                ('l_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Büyük Boy')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web_site.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
