# Generated by Django 5.1.7 on 2025-03-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='home_header_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ana sayfa Header button URL'),
        ),
    ]
