# Generated by Django 5.1.7 on 2025-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_alter_settings_home_header_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default='resim', upload_to='logo/'),
            preserve_default=False,
        ),
    ]
