# Generated by Django 5.1.7 on 2025-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtext',
            name='image',
            field=models.ImageField(default='resim', upload_to='sub-text/'),
            preserve_default=False,
        ),
    ]
